### ISSUE TITLE
Kännyvahvistukseen "vastaa A"

### ISSUE THREAD

**Issue by klaalo** [CSC-IT-Center-for-Science/stepup-proxy#1]
Proxy näyttää web-sivulla: tunnistuspyyntö xyz12345 tarvitsee vahvistuksen matkapuhelimella. Vastaa matkapuhelimeen tulleeseen viestiin.

Kännyyn lähetettävässä tekstiviestissä on edellinen koodi ja ohje: "vahvista vastaamalla A". Vastaaminen tökkää prosessin eteenpäin.

**Comment by jalauros** [comment]
On tehty joskus syksyllä jo eiks vaan?
