### ISSUE TITLE
TOTP-softan osalta agnostinen

### ISSUE THREAD

**Issue by atuomi** [CSC-IT-Center-for-Science/stepup-proxy#11]
Poistetaan viittaukset Google Authenticatoriin. Käytetään nyt vaikka termiä "Kertakäyttösalasana" aluksi.

**Comment by jalauros** [comment]
Mihin viittaat?

**Comment by atuomi** [comment]
![sieppaa](https://cloud.githubusercontent.com/assets/10530106/20515236/4e14ad2c-b099-11e6-8de1-f0473f510b0d.PNG)

**Comment by jalauros** [comment]
Tuo ei ole softamuutos. Deployment voi nimetä niinkuin haluaa.
